version: "3.7"

services:
  traefik:
    image: "traefik:v2.0.4"
    command:
      #- --log.level=DEBUG
      #- --entrypoints.web.address=:80
      #- --entrypoints.websecure.address=:443
      #- --providers.docker
      #- --api
      #- --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      #- --certificatesresolvers.leresolver.acme.email=${TRAEFIK_ACME_EMAIL}
      #- --certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json
      #- --certificatesresolvers.leresolver.acme.tlschallenge=true
      
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #- "./acme.json:/acme.json"
      #- ./letsencrypt:/letsencrypt
      - letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.my-app.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD_HASH}"
      - "traefik.http.middlewares.test-ipwhitelist.ipwhitelist.sourcerange=${TRAEFIK_IP_WHITELIST}"

      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  proxy:
    external: true
  internal:
    external: false

volumes:
  letsencrypt:
