version: '3.3'

services:
  traefik:
    image: traefik:v2.0.4
    container_name: "traefik"
    restart: unless-stopped
    command:
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      # CertificateResolvers
      #- --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true     
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.my-app.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=admin:$$apr1$$yRb7Usus$$2fhN5HA0p3Tkrgu2eJvD21"

      # global redirect to https
      #- "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      #- "traefik.http.routers.http-catchall.entrypoints=web"
      #- "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    container_name: "whoami"
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      #- "traefik.http.routers.whoami.middlewares=auth"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=leresolver"
      #- "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$yRb7Usus$$2fhN5HA0p3Tkrgu2eJvD21"
 
# touch acme.json; chmod 600 acme.json
