global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
providers:
  docker: {}
entryPoints:
  web:
    # Listen on port 80 for incoming requests
    address: :80
  websecure:
    # Listen on port 443 for incoming requests
    address: :443
api: {}
